import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Lang = 'fr' | 'en' | 'zh' | 'es' | 'ru' | 'ar' | 'ja' | 'de'

export const LANGUAGES: { code: Lang; label: string; flag: string; dir: 'ltr' | 'rtl' }[] = [
  { code: 'fr', label: 'Français',  flag: '🇫🇷', dir: 'ltr' },
  { code: 'en', label: 'English',   flag: '🇬🇧', dir: 'ltr' },
  { code: 'zh', label: '中文',       flag: '🇨🇳', dir: 'ltr' },
  { code: 'es', label: 'Español',   flag: '🇪🇸', dir: 'ltr' },
  { code: 'ru', label: 'Русский',   flag: '🇷🇺', dir: 'ltr' },
  { code: 'ar', label: 'العربية',   flag: '🇸🇦', dir: 'rtl' },
  { code: 'ja', label: '日本語',     flag: '🇯🇵', dir: 'ltr' },
  { code: 'de', label: 'Deutsch',   flag: '🇩🇪', dir: 'ltr' },
]

// ─── Translation table ────────────────────────────────────────────────────────
type T = Record<string, string>
const t_fr: T = {
  // Nav
  'nav.heritage':    'Héritage',
  'nav.collections': 'Collections',
  'nav.maison':      'Maison de Celle',
  'nav.olfactory':   'Notes Olfactives',
  'nav.groupbuy':    'Offres Groupées',
  'nav.creator':     'Carte Créateur',
  'nav.contact':     'Contact',
  // Hero
  'hero.tagline':    'Depuis 1802',
  'hero.quote':      '"Une goutte de parfum, une demi-page d\'histoire de France."',
  'hero.cta':        'Découvrir',
  'hero.maison_cta': 'Maison de Celle',
  // Heritage
  'heritage.title':           'Notre Héritage',
  'heritage.subtitle':        'Deux Siècles de Parfumerie Française',
  'heritage.intro':           "La Maison LA CELLE est l'une des rares parfumeries françaises à avoir traversé deux siècles d'histoire sans jamais changer de mains familiales.",
  'heritage.connections':     'Connexions Historiques',
  'heritage.defunct_title':   'Les Maisons Disparues Qui Nous Ont Inspirés',
  'heritage.defunct_subtitle':'Ces maisons disparues ont co-écrit avec nous l\'histoire de la parfumerie française',
  // Collections
  'collections.title':      'Nos Collections',
  'collections.subtitle':   'L\'Art de la Parfumerie Française',
  'collections.top':        'Notes de Tête',
  'collections.heart':      'Notes de Cœur',
  'collections.base':       'Notes de Fond',
  'collections.add_cart':   'Ajouter au Panier',
  'collections.discover':   'Découvrir',
  'collections.supreme':    'Collection Suprême',
  'collections.maison_cta': 'Maison de Celle',
  'collections.maison_desc':"La collection la plus exclusive de la Maison, réservée aux connaisseurs les plus exigeants.",
  // Maison
  'maison.title':              'Maison de Celle',
  'maison.subtitle':           'L\'Excellence Absolue',
  'maison.philosophy':         'La Philosophie Suprême',
  'maison.per_creation':       'Exemplaires par Création',
  'maison.natural':            'Essences Naturelles',
  'maison.crystal':            'Saint-Louis Cristal',
  'maison.craftsmanship':      'L\'Artisanat',
  'maison.craftsmanship_title':'Le Savoir-Faire des Maîtres Parfumeurs',
  'maison.consultation':       'Service Exclusif',
  'maison.consultation_title': 'Consultation Privée',
  'maison.consultation_desc':  "Pour l'acquisition d'une création Maison de Celle, nous vous invitons à prendre rendez-vous avec notre directeur artistique.",
  'maison.book':               'Prendre Rendez-vous',
  // Olfactory
  'olfactory.title':              'Notes Olfactives',
  'olfactory.subtitle':           'Carnets de l\'Atelier',
  'olfactory.intro':              "Depuis 1802, les maîtres parfumeurs consignent méticuleusement leurs découvertes olfactives dans des carnets reliés en cuir de Cordoue.",
  'olfactory.ingredients':        'Ingrédients Rares',
  'olfactory.ingredients_subtitle':'Les Matières Premières d\'Exception',
  'olfactory.training':           'Formation',
  'olfactory.training_title':     'L\'École de Parfumerie LA CELLE',
  'olfactory.training_desc':      "Depuis 1847, la Maison forme ses propres maîtres parfumeurs selon une tradition orale transmise de génération en génération.",
  // Group Buy
  'groupbuy.title':         'Offres Groupées',
  'groupbuy.subtitle':      'Parfums d\'Exception à Prix Privilégiés',
  'groupbuy.desc':          'Rejoignez un groupe d\'achat et bénéficiez de tarifs exclusifs. Plus le groupe est grand, plus la remise est importante.',
  'groupbuy.join':          'Rejoindre',
  'groupbuy.share':         'Partager',
  'groupbuy.people':        'personnes',
  'groupbuy.target':        'Objectif',
  'groupbuy.discount':      'Remise',
  'groupbuy.expires':       'Expire dans',
  'groupbuy.original':      'Prix original',
  'groupbuy.group_price':   'Prix groupé',
  'groupbuy.joined':        'ont rejoint ce groupe',
  'groupbuy.flash':         '⚡ Offre Flash',
  'groupbuy.mega':          '🔥 Méga Groupe',
  'groupbuy.standard':      '👥 Groupe Standard',
  'groupbuy.success':       'Vous avez rejoint le groupe !',
  'groupbuy.share_whatsapp':'Partager sur WhatsApp',
  'groupbuy.share_telegram':'Partager sur Telegram',
  'groupbuy.copy_link':     'Copier le lien',
  'groupbuy.copied':        'Lien copié !',
  'groupbuy.next_tier':     'Prochain palier',
  'groupbuy.more_needed':   'personnes de plus pour',
  'groupbuy.join_now':      'Rejoindre Maintenant',
  'groupbuy.amount':        'Montant (€)',
  'groupbuy.confirm_join':  'Confirmer',
  'groupbuy.tier_label':    'Palier',
  'groupbuy.progress':      'Progression',
  'groupbuy.how_works':     'Comment ça marche ?',
  'groupbuy.step1':         'Choisissez un parfum',
  'groupbuy.step1_desc':    'Sélectionnez une création LA CELLE et rejoignez un groupe d\'achat actif.',
  'groupbuy.step2':         'Invitez vos proches',
  'groupbuy.step2_desc':    'Partagez votre lien unique sur WhatsApp, Telegram ou par email.',
  'groupbuy.step3':         'Profitez du tarif groupé',
  'groupbuy.step3_desc':    'Plus le groupe est grand, plus la remise est importante — jusqu\'à 50% !',
  // Creator Card
  'creator.title':            'Carte Créateur',
  'creator.subtitle':         'Programme Ambassadeur LA CELLE',
  'creator.desc':             'Devenez ambassadeur de la Maison LA CELLE. Partagez notre univers olfactif et gagnez des récompenses exclusives.',
  'creator.apply':            'Devenir Ambassadeur',
  'creator.my_card':          'Ma Carte',
  'creator.stats':            'Statistiques',
  'creator.submissions':      'Soumissions',
  'creator.rewards':          'Récompenses',
  'creator.followers':        'Abonnés',
  'creator.credit':           'Crédit Disponible',
  'creator.tier':             'Niveau',
  'creator.submit_content':   'Soumettre du Contenu',
  'creator.platform':         'Plateforme',
  'creator.handle':           'Identifiant',
  'creator.content_url':      'URL du Contenu',
  'creator.description':      'Description',
  'creator.submit':           'Soumettre',
  'creator.pending':          'En attente',
  'creator.approved':         'Approuvé',
  'creator.rejected':         'Refusé',
  'creator.how_works':        'Comment fonctionne la Carte Créateur ?',
  'creator.step1':            'Postulez',
  'creator.step1_desc':       'Soumettez vos comptes de réseaux sociaux. Notre IA évalue votre profil.',
  'creator.step2':            'Recevez votre carte',
  'creator.step2_desc':       'Une carte virtuelle avec une limite de crédit selon votre audience.',
  'creator.step3':            'Créez du contenu',
  'creator.step3_desc':       'Partagez l\'univers LA CELLE et remboursez via vos publications.',
  'creator.add_account':      'Ajouter un compte',
  'creator.total_followers':  'Total abonnés',
  'creator.reviewing':        'Analyse en cours...',
  'creator.min_followers':    'Minimum 10 000 abonnés requis',
  // Contact
  'contact.title':   'Contact',
  'contact.subtitle':'Nous Contacter',
  'contact.paris':   'Boutique Paris',
  'contact.grasse':  'Atelier Grasse',
  'contact.china':   'Représentant Chine',
  'contact.name':    'Nom',
  'contact.email':   'Email',
  'contact.subject': 'Sujet',
  'contact.message': 'Message',
  'contact.send':    'Envoyer',
  'contact.sent':    'Message envoyé',
  // Footer
  'footer.tagline':          '"Une goutte de parfum, une demi-page d\'histoire de France."',
  'footer.maison':           'Maison',
  'footer.collections_label':'Collections',
  'footer.contact_label':    'Contact',
  'footer.rights':           '© 2024 LA CELLE PARIS. Maison fondée en 1802. Tous droits réservés.',
  // Common
  'common.loading': 'Chargement...',
  'common.error':   'Une erreur s\'est produite',
  'common.back':    'Retour',
  'common.close':   'Fermer',
  'common.save':    'Enregistrer',
  'common.cancel':  'Annuler',
  'common.confirm': 'Confirmer',
}

const t_en: T = {
  'nav.heritage':    'Heritage',
  'nav.collections': 'Collections',
  'nav.maison':      'Maison de Celle',
  'nav.olfactory':   'Olfactory Notes',
  'nav.groupbuy':    'Group Offers',
  'nav.creator':     'Creator Card',
  'nav.contact':     'Contact',
  'hero.tagline':    'Since 1802',
  'hero.quote':      '"A drop of perfume, half a page of French history."',
  'hero.cta':        'Discover',
  'hero.maison_cta': 'Maison de Celle',
  'heritage.title':           'Our Heritage',
  'heritage.subtitle':        'Two Centuries of French Perfumery',
  'heritage.intro':           'LA CELLE is one of the rare French perfumeries to have crossed two centuries of history without ever changing family hands.',
  'heritage.connections':     'Historical Connections',
  'heritage.defunct_title':   'The Vanished Houses That Inspired Us',
  'heritage.defunct_subtitle':'These disappeared houses co-wrote with us the history of French perfumery',
  'collections.title':      'Our Collections',
  'collections.subtitle':   'The Art of French Perfumery',
  'collections.top':        'Top Notes',
  'collections.heart':      'Heart Notes',
  'collections.base':       'Base Notes',
  'collections.add_cart':   'Add to Cart',
  'collections.discover':   'Discover',
  'collections.supreme':    'Supreme Collection',
  'collections.maison_cta': 'Maison de Celle',
  'collections.maison_desc':'The most exclusive collection of the House, reserved for the most discerning connoisseurs.',
  'maison.title':              'Maison de Celle',
  'maison.subtitle':           'Absolute Excellence',
  'maison.philosophy':         'The Supreme Philosophy',
  'maison.per_creation':       'Pieces per Creation',
  'maison.natural':            'Natural Essences',
  'maison.crystal':            'Saint-Louis Crystal',
  'maison.craftsmanship':      'Craftsmanship',
  'maison.craftsmanship_title':'The Mastery of Master Perfumers',
  'maison.consultation':       'Exclusive Service',
  'maison.consultation_title': 'Private Consultation',
  'maison.consultation_desc':  'For the acquisition of a Maison de Celle creation, we invite you to schedule a private consultation with our artistic director.',
  'maison.book':               'Book Appointment',
  'olfactory.title':              'Olfactory Notes',
  'olfactory.subtitle':           'Workshop Journals',
  'olfactory.intro':              'Since 1802, the master perfumers of Maison LA CELLE have meticulously recorded their olfactory discoveries in Cordovan leather-bound notebooks.',
  'olfactory.ingredients':        'Rare Ingredients',
  'olfactory.ingredients_subtitle':'Exceptional Raw Materials',
  'olfactory.training':           'Training',
  'olfactory.training_title':     'The LA CELLE School of Perfumery',
  'olfactory.training_desc':      'Since 1847, the House trains its own master perfumers according to an oral tradition passed down from generation to generation.',
  'groupbuy.title':         'Group Offers',
  'groupbuy.subtitle':      'Exceptional Fragrances at Privileged Prices',
  'groupbuy.desc':          'Join a buying group and enjoy exclusive rates on our creations. The larger the group, the greater the discount.',
  'groupbuy.join':          'Join',
  'groupbuy.share':         'Share',
  'groupbuy.people':        'people',
  'groupbuy.target':        'Target',
  'groupbuy.discount':      'Discount',
  'groupbuy.expires':       'Expires in',
  'groupbuy.original':      'Original price',
  'groupbuy.group_price':   'Group price',
  'groupbuy.joined':        'have joined this group',
  'groupbuy.flash':         '⚡ Flash Offer',
  'groupbuy.mega':          '🔥 Mega Group',
  'groupbuy.standard':      '👥 Standard Group',
  'groupbuy.success':       'You joined the group!',
  'groupbuy.share_whatsapp':'Share on WhatsApp',
  'groupbuy.share_telegram':'Share on Telegram',
  'groupbuy.copy_link':     'Copy link',
  'groupbuy.copied':        'Link copied!',
  'groupbuy.next_tier':     'Next tier',
  'groupbuy.more_needed':   'more people for',
  'groupbuy.join_now':      'Join Now',
  'groupbuy.amount':        'Amount (€)',
  'groupbuy.confirm_join':  'Confirm',
  'groupbuy.tier_label':    'Tier',
  'groupbuy.progress':      'Progress',
  'groupbuy.how_works':     'How does it work?',
  'groupbuy.step1':         'Choose a fragrance',
  'groupbuy.step1_desc':    'Select a LA CELLE creation and join an active buying group.',
  'groupbuy.step2':         'Invite your friends',
  'groupbuy.step2_desc':    'Share your unique link on WhatsApp, Telegram or by email.',
  'groupbuy.step3':         'Enjoy the group price',
  'groupbuy.step3_desc':    'The larger the group, the greater the discount — up to 50%!',
  'creator.title':            'Creator Card',
  'creator.subtitle':         'LA CELLE Ambassador Programme',
  'creator.desc':             'Become an ambassador of Maison LA CELLE. Share our olfactory universe and earn exclusive rewards.',
  'creator.apply':            'Become Ambassador',
  'creator.my_card':          'My Card',
  'creator.stats':            'Statistics',
  'creator.submissions':      'Submissions',
  'creator.rewards':          'Rewards',
  'creator.followers':        'Followers',
  'creator.credit':           'Available Credit',
  'creator.tier':             'Tier',
  'creator.submit_content':   'Submit Content',
  'creator.platform':         'Platform',
  'creator.handle':           'Handle',
  'creator.content_url':      'Content URL',
  'creator.description':      'Description',
  'creator.submit':           'Submit',
  'creator.pending':          'Pending',
  'creator.approved':         'Approved',
  'creator.rejected':         'Rejected',
  'creator.how_works':        'How does the Creator Card work?',
  'creator.step1':            'Apply',
  'creator.step1_desc':       'Submit your social media accounts. Our AI evaluates your profile.',
  'creator.step2':            'Receive your card',
  'creator.step2_desc':       'A virtual card with a credit limit based on your audience size.',
  'creator.step3':            'Create content',
  'creator.step3_desc':       'Share the LA CELLE universe and repay through your publications.',
  'creator.add_account':      'Add account',
  'creator.total_followers':  'Total followers',
  'creator.reviewing':        'Analysing...',
  'creator.min_followers':    'Minimum 10,000 followers required',
  'contact.title':   'Contact',
  'contact.subtitle':'Get in Touch',
  'contact.paris':   'Paris Boutique',
  'contact.grasse':  'Grasse Atelier',
  'contact.china':   'China Representative',
  'contact.name':    'Name',
  'contact.email':   'Email',
  'contact.subject': 'Subject',
  'contact.message': 'Message',
  'contact.send':    'Send',
  'contact.sent':    'Message sent',
  'footer.tagline':          '"A drop of perfume, half a page of French history."',
  'footer.maison':           'Maison',
  'footer.collections_label':'Collections',
  'footer.contact_label':    'Contact',
  'footer.rights':           '© 2024 LA CELLE PARIS. House founded in 1802. All rights reserved.',
  'common.loading': 'Loading...',
  'common.error':   'Something went wrong',
  'common.back':    'Back',
  'common.close':   'Close',
  'common.save':    'Save',
  'common.cancel':  'Cancel',
  'common.confirm': 'Confirm',
}

const t_zh: T = {
  'nav.heritage':    '品牌历史',
  'nav.collections': '系列香水',
  'nav.maison':      '高端系列',
  'nav.olfactory':   '调香笔记',
  'nav.groupbuy':    '拼团优惠',
  'nav.creator':     '创作者卡片',
  'nav.contact':     '联系我们',
  'hero.tagline':    '自1802年',
  'hero.quote':      '"一滴香水，半部法国史。"',
  'hero.cta':        '探索',
  'hero.maison_cta': 'Maison de Celle',
  'heritage.title':           '品牌历史',
  'heritage.subtitle':        '两个世纪的法国香水艺术',
  'heritage.intro':           'LA CELLE是少数几个两个世纪来始终保持家族传承的法国香水品牌之一。',
  'heritage.connections':     '历史渊源',
  'heritage.defunct_title':   '那些已消逝的香水世家',
  'heritage.defunct_subtitle':'那些已消逝的香水世家，曾与我们共同书写法国香水史',
  'collections.title':      '我们的系列',
  'collections.subtitle':   '法国香水艺术',
  'collections.top':        '前调',
  'collections.heart':      '中调',
  'collections.base':       '后调',
  'collections.add_cart':   '加入购物车',
  'collections.discover':   '探索',
  'collections.supreme':    '至高系列',
  'collections.maison_cta': 'Maison de Celle',
  'collections.maison_desc':'品牌最尊贵的系列，专为最挑剔的鉴赏家而设。',
  'maison.title':              'Maison de Celle',
  'maison.subtitle':           '极致卓越',
  'maison.philosophy':         '至高哲学',
  'maison.per_creation':       '每款限量',
  'maison.natural':            '天然香精',
  'maison.crystal':            '圣路易斯水晶',
  'maison.craftsmanship':      '工艺',
  'maison.craftsmanship_title':'调香大师的精湛工艺',
  'maison.consultation':       '专属服务',
  'maison.consultation_title': '私人咨询',
  'maison.consultation_desc':  '购买Maison de Celle系列，我们邀请您与艺术总监进行私人咨询。',
  'maison.book':               '预约咨询',
  'olfactory.title':              '调香笔记',
  'olfactory.subtitle':           '工坊手记',
  'olfactory.intro':              '自1802年起，LA CELLE的调香大师们将每一次嗅觉发现都细心记录在科尔多瓦皮革装订的笔记本中。',
  'olfactory.ingredients':        '稀有香料',
  'olfactory.ingredients_subtitle':'珍稀原材料',
  'olfactory.training':           '培训',
  'olfactory.training_title':     'LA CELLE调香学院',
  'olfactory.training_desc':      '自1847年起，品牌按照代代相传的口头传统培训自己的调香大师。',
  'groupbuy.title':         '拼团优惠',
  'groupbuy.subtitle':      '顶级香水，专属团购价格',
  'groupbuy.desc':          '加入拼团，享受我们创作的专属优惠。团购人数越多，折扣越大。',
  'groupbuy.join':          '参与拼团',
  'groupbuy.share':         '分享',
  'groupbuy.people':        '人',
  'groupbuy.target':        '目标',
  'groupbuy.discount':      '折扣',
  'groupbuy.expires':       '剩余时间',
  'groupbuy.original':      '原价',
  'groupbuy.group_price':   '团购价',
  'groupbuy.joined':        '人已参团',
  'groupbuy.flash':         '⚡ 闪团',
  'groupbuy.mega':          '🔥 万人团',
  'groupbuy.standard':      '👥 标准拼团',
  'groupbuy.success':       '成功加入拼团！',
  'groupbuy.share_whatsapp':'分享到WhatsApp',
  'groupbuy.share_telegram':'分享到Telegram',
  'groupbuy.copy_link':     '复制链接',
  'groupbuy.copied':        '链接已复制！',
  'groupbuy.next_tier':     '下一档',
  'groupbuy.more_needed':   '人即可享受',
  'groupbuy.join_now':      '立即参团',
  'groupbuy.amount':        '金额（€）',
  'groupbuy.confirm_join':  '确认',
  'groupbuy.tier_label':    '档位',
  'groupbuy.progress':      '进度',
  'groupbuy.how_works':     '如何参与？',
  'groupbuy.step1':         '选择香水',
  'groupbuy.step1_desc':    '选择一款LA CELLE香水，加入当前活跃的拼团。',
  'groupbuy.step2':         '邀请好友',
  'groupbuy.step2_desc':    '通过WhatsApp、Telegram或邮件分享您的专属链接。',
  'groupbuy.step3':         '享受团购价',
  'groupbuy.step3_desc':    '参团人数越多，折扣越大——最高可达50%！',
  'creator.title':            '创作者卡片',
  'creator.subtitle':         'LA CELLE品牌大使计划',
  'creator.desc':             '成为LA CELLE品牌大使，分享我们的嗅觉世界，赢取专属奖励。',
  'creator.apply':            '申请成为大使',
  'creator.my_card':          '我的卡片',
  'creator.stats':            '数据统计',
  'creator.submissions':      '内容提交',
  'creator.rewards':          '奖励',
  'creator.followers':        '粉丝数',
  'creator.credit':           '可用额度',
  'creator.tier':             '等级',
  'creator.submit_content':   '提交内容',
  'creator.platform':         '平台',
  'creator.handle':           '账号',
  'creator.content_url':      '内容链接',
  'creator.description':      '描述',
  'creator.submit':           '提交',
  'creator.pending':          '审核中',
  'creator.approved':         '已通过',
  'creator.rejected':         '已拒绝',
  'creator.how_works':        '创作者卡片如何运作？',
  'creator.step1':            '申请',
  'creator.step1_desc':       '提交您的社交媒体账号，我们的AI将评估您的资质。',
  'creator.step2':            '获得卡片',
  'creator.step2_desc':       '根据您的粉丝量获得相应额度的虚拟信用卡。',
  'creator.step3':            '创作内容',
  'creator.step3_desc':       '分享LA CELLE的世界，通过发布内容偿还消费。',
  'creator.add_account':      '添加账号',
  'creator.total_followers':  '总粉丝数',
  'creator.reviewing':        '分析中...',
  'creator.min_followers':    '最少需要10,000粉丝',
  'contact.title':   '联系我们',
  'contact.subtitle':'与我们联系',
  'contact.paris':   '巴黎精品店',
  'contact.grasse':  '格拉斯工坊',
  'contact.china':   '中国总代理',
  'contact.name':    '姓名',
  'contact.email':   '邮箱',
  'contact.subject': '主题',
  'contact.message': '留言',
  'contact.send':    '发送',
  'contact.sent':    '消息已发送',
  'footer.tagline':          '"一滴香水，半部法国史。"',
  'footer.maison':           '品牌',
  'footer.collections_label':'系列',
  'footer.contact_label':    '联系',
  'footer.rights':           '© 2024 LA CELLE PARIS. 创立于1802年。版权所有。',
  'common.loading': '加载中...',
  'common.error':   '出现错误',
  'common.back':    '返回',
  'common.close':   '关闭',
  'common.save':    '保存',
  'common.cancel':  '取消',
  'common.confirm': '确认',
}

const t_es: T = {
  'nav.heritage':    'Patrimonio',
  'nav.collections': 'Colecciones',
  'nav.maison':      'Maison de Celle',
  'nav.olfactory':   'Notas Olfativas',
  'nav.groupbuy':    'Ofertas Grupales',
  'nav.creator':     'Tarjeta Creador',
  'nav.contact':     'Contacto',
  'hero.tagline':    'Desde 1802',
  'hero.quote':      '"Una gota de perfume, media página de historia de Francia."',
  'hero.cta':        'Descubrir',
  'hero.maison_cta': 'Maison de Celle',
  'heritage.title':           'Nuestro Patrimonio',
  'heritage.subtitle':        'Dos Siglos de Perfumería Francesa',
  'heritage.intro':           'LA CELLE es una de las raras perfumerías francesas que ha atravesado dos siglos de historia sin cambiar jamás de manos familiares.',
  'heritage.connections':     'Conexiones Históricas',
  'heritage.defunct_title':   'Las Casas Desaparecidas que Nos Inspiraron',
  'heritage.defunct_subtitle':'Estas casas desaparecidas co-escribieron con nosotros la historia de la perfumería francesa',
  'collections.title':      'Nuestras Colecciones',
  'collections.subtitle':   'El Arte de la Perfumería Francesa',
  'collections.top':        'Notas de Salida',
  'collections.heart':      'Notas de Corazón',
  'collections.base':       'Notas de Fondo',
  'collections.add_cart':   'Añadir al Carrito',
  'collections.discover':   'Descubrir',
  'collections.supreme':    'Colección Suprema',
  'collections.maison_cta': 'Maison de Celle',
  'collections.maison_desc':'La colección más exclusiva de la Casa, reservada para los conocedores más exigentes.',
  'maison.title':              'Maison de Celle',
  'maison.subtitle':           'Excelencia Absoluta',
  'maison.philosophy':         'La Filosofía Suprema',
  'maison.per_creation':       'Ejemplares por Creación',
  'maison.natural':            'Esencias Naturales',
  'maison.crystal':            'Cristal Saint-Louis',
  'maison.craftsmanship':      'Artesanía',
  'maison.craftsmanship_title':'El Saber Hacer de los Maestros Perfumeros',
  'maison.consultation':       'Servicio Exclusivo',
  'maison.consultation_title': 'Consulta Privada',
  'maison.consultation_desc':  'Para la adquisición de una creación Maison de Celle, le invitamos a concertar una consulta privada.',
  'maison.book':               'Reservar Cita',
  'olfactory.title':              'Notas Olfativas',
  'olfactory.subtitle':           'Cuadernos del Taller',
  'olfactory.intro':              'Desde 1802, los maestros perfumeros de la Maison LA CELLE registran meticulosamente sus descubrimientos olfativos.',
  'olfactory.ingredients':        'Ingredientes Raros',
  'olfactory.ingredients_subtitle':'Materias Primas de Excepción',
  'olfactory.training':           'Formación',
  'olfactory.training_title':     'La Escuela de Perfumería LA CELLE',
  'olfactory.training_desc':      'Desde 1847, la Casa forma a sus propios maestros perfumeros según una tradición oral.',
  'groupbuy.title':         'Ofertas Grupales',
  'groupbuy.subtitle':      'Fragancias Excepcionales a Precios Privilegiados',
  'groupbuy.desc':          'Únase a un grupo de compra y disfrute de tarifas exclusivas. Cuanto mayor sea el grupo, mayor será el descuento.',
  'groupbuy.join':          'Unirse',
  'groupbuy.share':         'Compartir',
  'groupbuy.people':        'personas',
  'groupbuy.target':        'Objetivo',
  'groupbuy.discount':      'Descuento',
  'groupbuy.expires':       'Expira en',
  'groupbuy.original':      'Precio original',
  'groupbuy.group_price':   'Precio grupal',
  'groupbuy.joined':        'se han unido a este grupo',
  'groupbuy.flash':         '⚡ Oferta Flash',
  'groupbuy.mega':          '🔥 Mega Grupo',
  'groupbuy.standard':      '👥 Grupo Estándar',
  'groupbuy.success':       '¡Te has unido al grupo!',
  'groupbuy.share_whatsapp':'Compartir en WhatsApp',
  'groupbuy.share_telegram':'Compartir en Telegram',
  'groupbuy.copy_link':     'Copiar enlace',
  'groupbuy.copied':        '¡Enlace copiado!',
  'groupbuy.next_tier':     'Siguiente nivel',
  'groupbuy.more_needed':   'personas más para',
  'groupbuy.join_now':      'Unirse Ahora',
  'groupbuy.amount':        'Cantidad (€)',
  'groupbuy.confirm_join':  'Confirmar',
  'groupbuy.tier_label':    'Nivel',
  'groupbuy.progress':      'Progreso',
  'groupbuy.how_works':     '¿Cómo funciona?',
  'groupbuy.step1':         'Elige una fragancia',
  'groupbuy.step1_desc':    'Selecciona una creación LA CELLE y únete a un grupo de compra activo.',
  'groupbuy.step2':         'Invita a tus amigos',
  'groupbuy.step2_desc':    'Comparte tu enlace único en WhatsApp, Telegram o por email.',
  'groupbuy.step3':         'Disfruta del precio grupal',
  'groupbuy.step3_desc':    'Cuanto mayor sea el grupo, mayor será el descuento — ¡hasta el 50%!',
  'creator.title':            'Tarjeta Creador',
  'creator.subtitle':         'Programa Embajador LA CELLE',
  'creator.desc':             'Conviértase en embajador de la Maison LA CELLE y gane recompensas exclusivas.',
  'creator.apply':            'Ser Embajador',
  'creator.my_card':          'Mi Tarjeta',
  'creator.stats':            'Estadísticas',
  'creator.submissions':      'Envíos',
  'creator.rewards':          'Recompensas',
  'creator.followers':        'Seguidores',
  'creator.credit':           'Crédito Disponible',
  'creator.tier':             'Nivel',
  'creator.submit_content':   'Enviar Contenido',
  'creator.platform':         'Plataforma',
  'creator.handle':           'Usuario',
  'creator.content_url':      'URL del Contenido',
  'creator.description':      'Descripción',
  'creator.submit':           'Enviar',
  'creator.pending':          'Pendiente',
  'creator.approved':         'Aprobado',
  'creator.rejected':         'Rechazado',
  'creator.how_works':        '¿Cómo funciona la Tarjeta Creador?',
  'creator.step1':            'Solicita',
  'creator.step1_desc':       'Envía tus cuentas de redes sociales. Nuestra IA evalúa tu perfil.',
  'creator.step2':            'Recibe tu tarjeta',
  'creator.step2_desc':       'Una tarjeta virtual con límite de crédito según tu audiencia.',
  'creator.step3':            'Crea contenido',
  'creator.step3_desc':       'Comparte el universo LA CELLE y reembolsa a través de tus publicaciones.',
  'creator.add_account':      'Añadir cuenta',
  'creator.total_followers':  'Total seguidores',
  'creator.reviewing':        'Analizando...',
  'creator.min_followers':    'Mínimo 10.000 seguidores requeridos',
  'contact.title':   'Contacto',
  'contact.subtitle':'Contáctenos',
  'contact.paris':   'Boutique París',
  'contact.grasse':  'Taller Grasse',
  'contact.china':   'Representante China',
  'contact.name':    'Nombre',
  'contact.email':   'Correo',
  'contact.subject': 'Asunto',
  'contact.message': 'Mensaje',
  'contact.send':    'Enviar',
  'contact.sent':    'Mensaje enviado',
  'footer.tagline':          '"Una gota de perfume, media página de historia de Francia."',
  'footer.maison':           'Maison',
  'footer.collections_label':'Colecciones',
  'footer.contact_label':    'Contacto',
  'footer.rights':           '© 2024 LA CELLE PARIS. Casa fundada en 1802. Todos los derechos reservados.',
  'common.loading': 'Cargando...',
  'common.error':   'Algo salió mal',
  'common.back':    'Volver',
  'common.close':   'Cerrar',
  'common.save':    'Guardar',
  'common.cancel':  'Cancelar',
  'common.confirm': 'Confirmar',
}

const t_ru: T = {
  'nav.heritage':    'Наследие',
  'nav.collections': 'Коллекции',
  'nav.maison':      'Maison de Celle',
  'nav.olfactory':   'Ольфакторные Заметки',
  'nav.groupbuy':    'Групповые Покупки',
  'nav.creator':     'Карта Создателя',
  'nav.contact':     'Контакты',
  'hero.tagline':    'С 1802 года',
  'hero.quote':      '"Капля духов — полстраницы истории Франции."',
  'hero.cta':        'Открыть',
  'hero.maison_cta': 'Maison de Celle',
  'heritage.title':           'Наше Наследие',
  'heritage.subtitle':        'Два Века Французской Парфюмерии',
  'heritage.intro':           'LA CELLE — один из редких французских парфюмерных домов, прошедших через два века истории.',
  'heritage.connections':     'Исторические Связи',
  'heritage.defunct_title':   'Исчезнувшие Дома, Которые Нас Вдохновили',
  'heritage.defunct_subtitle':'Эти исчезнувшие дома вместе с нами писали историю французской парфюмерии',
  'collections.title':      'Наши Коллекции',
  'collections.subtitle':   'Искусство Французской Парфюмерии',
  'collections.top':        'Верхние Ноты',
  'collections.heart':      'Ноты Сердца',
  'collections.base':       'Базовые Ноты',
  'collections.add_cart':   'В Корзину',
  'collections.discover':   'Открыть',
  'collections.supreme':    'Высшая Коллекция',
  'collections.maison_cta': 'Maison de Celle',
  'collections.maison_desc':'Самая эксклюзивная коллекция Дома для самых взыскательных ценителей.',
  'maison.title':              'Maison de Celle',
  'maison.subtitle':           'Абсолютное Совершенство',
  'maison.philosophy':         'Высшая Философия',
  'maison.per_creation':       'Экземпляров на Творение',
  'maison.natural':            'Натуральные Эссенции',
  'maison.crystal':            'Хрусталь Saint-Louis',
  'maison.craftsmanship':      'Мастерство',
  'maison.craftsmanship_title':'Искусство Мастеров-Парфюмеров',
  'maison.consultation':       'Эксклюзивный Сервис',
  'maison.consultation_title': 'Частная Консультация',
  'maison.consultation_desc':  'Для приобретения творения Maison de Celle приглашаем на частную консультацию.',
  'maison.book':               'Записаться',
  'olfactory.title':              'Ольфакторные Заметки',
  'olfactory.subtitle':           'Дневники Мастерской',
  'olfactory.intro':              'С 1802 года мастера-парфюмеры тщательно записывают свои открытия в тетради, переплетённые в кордовскую кожу.',
  'olfactory.ingredients':        'Редкие Ингредиенты',
  'olfactory.ingredients_subtitle':'Исключительное Сырьё',
  'olfactory.training':           'Обучение',
  'olfactory.training_title':     'Школа Парфюмерии LA CELLE',
  'olfactory.training_desc':      'С 1847 года Дом готовит собственных мастеров по устной традиции.',
  'groupbuy.title':         'Групповые Покупки',
  'groupbuy.subtitle':      'Исключительные Ароматы по Привилегированным Ценам',
  'groupbuy.desc':          'Присоединяйтесь к группе покупателей и пользуйтесь эксклюзивными ценами.',
  'groupbuy.join':          'Присоединиться',
  'groupbuy.share':         'Поделиться',
  'groupbuy.people':        'человек',
  'groupbuy.target':        'Цель',
  'groupbuy.discount':      'Скидка',
  'groupbuy.expires':       'Истекает через',
  'groupbuy.original':      'Обычная цена',
  'groupbuy.group_price':   'Групповая цена',
  'groupbuy.joined':        'присоединились к группе',
  'groupbuy.flash':         '⚡ Флэш-предложение',
  'groupbuy.mega':          '🔥 Мега-группа',
  'groupbuy.standard':      '👥 Стандартная группа',
  'groupbuy.success':       'Вы присоединились к группе!',
  'groupbuy.share_whatsapp':'Поделиться в WhatsApp',
  'groupbuy.share_telegram':'Поделиться в Telegram',
  'groupbuy.copy_link':     'Копировать ссылку',
  'groupbuy.copied':        'Ссылка скопирована!',
  'groupbuy.next_tier':     'Следующий уровень',
  'groupbuy.more_needed':   'человек ещё для',
  'groupbuy.join_now':      'Присоединиться',
  'groupbuy.amount':        'Сумма (€)',
  'groupbuy.confirm_join':  'Подтвердить',
  'groupbuy.tier_label':    'Уровень',
  'groupbuy.progress':      'Прогресс',
  'groupbuy.how_works':     'Как это работает?',
  'groupbuy.step1':         'Выберите аромат',
  'groupbuy.step1_desc':    'Выберите создание LA CELLE и присоединитесь к активной группе.',
  'groupbuy.step2':         'Пригласите друзей',
  'groupbuy.step2_desc':    'Поделитесь уникальной ссылкой в WhatsApp, Telegram или по email.',
  'groupbuy.step3':         'Наслаждайтесь групповой ценой',
  'groupbuy.step3_desc':    'Чем больше группа, тем больше скидка — до 50%!',
  'creator.title':            'Карта Создателя',
  'creator.subtitle':         'Программа Посла LA CELLE',
  'creator.desc':             'Станьте послом Maison LA CELLE и получайте эксклюзивные награды.',
  'creator.apply':            'Стать Послом',
  'creator.my_card':          'Моя Карта',
  'creator.stats':            'Статистика',
  'creator.submissions':      'Публикации',
  'creator.rewards':          'Награды',
  'creator.followers':        'Подписчики',
  'creator.credit':           'Доступный Кредит',
  'creator.tier':             'Уровень',
  'creator.submit_content':   'Отправить Контент',
  'creator.platform':         'Платформа',
  'creator.handle':           'Аккаунт',
  'creator.content_url':      'URL Контента',
  'creator.description':      'Описание',
  'creator.submit':           'Отправить',
  'creator.pending':          'На рассмотрении',
  'creator.approved':         'Одобрено',
  'creator.rejected':         'Отклонено',
  'creator.how_works':        'Как работает Карта Создателя?',
  'creator.step1':            'Подайте заявку',
  'creator.step1_desc':       'Отправьте свои аккаунты в соцсетях. ИИ оценит ваш профиль.',
  'creator.step2':            'Получите карту',
  'creator.step2_desc':       'Виртуальная карта с кредитным лимитом по размеру аудитории.',
  'creator.step3':            'Создавайте контент',
  'creator.step3_desc':       'Делитесь миром LA CELLE и погашайте кредит публикациями.',
  'creator.add_account':      'Добавить аккаунт',
  'creator.total_followers':  'Всего подписчиков',
  'creator.reviewing':        'Анализ...',
  'creator.min_followers':    'Минимум 10 000 подписчиков',
  'contact.title':   'Контакты',
  'contact.subtitle':'Свяжитесь с Нами',
  'contact.paris':   'Бутик Париж',
  'contact.grasse':  'Ателье Грасс',
  'contact.china':   'Представитель в Китае',
  'contact.name':    'Имя',
  'contact.email':   'Email',
  'contact.subject': 'Тема',
  'contact.message': 'Сообщение',
  'contact.send':    'Отправить',
  'contact.sent':    'Сообщение отправлено',
  'footer.tagline':          '"Капля духов — полстраницы истории Франции."',
  'footer.maison':           'Maison',
  'footer.collections_label':'Коллекции',
  'footer.contact_label':    'Контакты',
  'footer.rights':           '© 2024 LA CELLE PARIS. Дом основан в 1802 году. Все права защищены.',
  'common.loading': 'Загрузка...',
  'common.error':   'Произошла ошибка',
  'common.back':    'Назад',
  'common.close':   'Закрыть',
  'common.save':    'Сохранить',
  'common.cancel':  'Отмена',
  'common.confirm': 'Подтвердить',
}

const t_ar: T = {
  'nav.heritage':    'الإرث',
  'nav.collections': 'المجموعات',
  'nav.maison':      'Maison de Celle',
  'nav.olfactory':   'الملاحظات العطرية',
  'nav.groupbuy':    'الشراء الجماعي',
  'nav.creator':     'بطاقة المبدع',
  'nav.contact':     'اتصل بنا',
  'hero.tagline':    'منذ عام 1802',
  'hero.quote':      '"قطرة عطر، نصف صفحة من تاريخ فرنسا."',
  'hero.cta':        'اكتشف',
  'hero.maison_cta': 'Maison de Celle',
  'heritage.title':           'إرثنا',
  'heritage.subtitle':        'قرنان من صناعة العطور الفرنسية',
  'heritage.intro':           'تُعدّ LA CELLE من النادر من دور العطور الفرنسية التي اجتازت قرنين من التاريخ.',
  'heritage.connections':     'الروابط التاريخية',
  'heritage.defunct_title':   'الدور المنقرضة التي ألهمتنا',
  'heritage.defunct_subtitle':'كتبت هذه الدور معنا تاريخ العطور الفرنسية',
  'collections.title':      'مجموعاتنا',
  'collections.subtitle':   'فن صناعة العطور الفرنسية',
  'collections.top':        'النوتات العلوية',
  'collections.heart':      'نوتات القلب',
  'collections.base':       'النوتات القاعدية',
  'collections.add_cart':   'أضف إلى السلة',
  'collections.discover':   'اكتشف',
  'collections.supreme':    'المجموعة العليا',
  'collections.maison_cta': 'Maison de Celle',
  'collections.maison_desc':'أكثر مجموعات الدار حصرية للعارفين.',
  'maison.title':              'Maison de Celle',
  'maison.subtitle':           'التميز المطلق',
  'maison.philosophy':         'الفلسفة العليا',
  'maison.per_creation':       'نسخة لكل إبداع',
  'maison.natural':            'جوهر طبيعي',
  'maison.crystal':            'بلور Saint-Louis',
  'maison.craftsmanship':      'الحرفية',
  'maison.craftsmanship_title':'براعة أساتذة العطور',
  'maison.consultation':       'خدمة حصرية',
  'maison.consultation_title': 'استشارة خاصة',
  'maison.consultation_desc':  'لاقتناء إبداع من Maison de Celle، ندعوكم لاستشارة خاصة.',
  'maison.book':               'احجز موعداً',
  'olfactory.title':              'الملاحظات العطرية',
  'olfactory.subtitle':           'مذكرات الورشة',
  'olfactory.intro':              'منذ عام 1802، يسجّل أساتذة العطور اكتشافاتهم في دفاتر مجلدة بجلد قرطبة.',
  'olfactory.ingredients':        'مكونات نادرة',
  'olfactory.ingredients_subtitle':'مواد خام استثنائية',
  'olfactory.training':           'التدريب',
  'olfactory.training_title':     'مدرسة العطور LA CELLE',
  'olfactory.training_desc':      'منذ عام 1847، تُدرّب الدار أساتذة عطورها وفق تقليد شفهي متوارث.',
  'groupbuy.title':         'الشراء الجماعي',
  'groupbuy.subtitle':      'عطور استثنائية بأسعار مميزة',
  'groupbuy.desc':          'انضم إلى مجموعة شراء واستمتع بأسعار حصرية.',
  'groupbuy.join':          'انضم',
  'groupbuy.share':         'شارك',
  'groupbuy.people':        'أشخاص',
  'groupbuy.target':        'الهدف',
  'groupbuy.discount':      'خصم',
  'groupbuy.expires':       'ينتهي خلال',
  'groupbuy.original':      'السعر الأصلي',
  'groupbuy.group_price':   'سعر المجموعة',
  'groupbuy.joined':        'انضموا إلى هذه المجموعة',
  'groupbuy.flash':         '⚡ عرض خاطف',
  'groupbuy.mega':          '🔥 مجموعة ضخمة',
  'groupbuy.standard':      '👥 مجموعة عادية',
  'groupbuy.success':       'انضممت إلى المجموعة!',
  'groupbuy.share_whatsapp':'شارك على واتساب',
  'groupbuy.share_telegram':'شارك على تيليغرام',
  'groupbuy.copy_link':     'نسخ الرابط',
  'groupbuy.copied':        'تم نسخ الرابط!',
  'groupbuy.next_tier':     'المستوى التالي',
  'groupbuy.more_needed':   'أشخاص أكثر لـ',
  'groupbuy.join_now':      'انضم الآن',
  'groupbuy.amount':        'المبلغ (€)',
  'groupbuy.confirm_join':  'تأكيد',
  'groupbuy.tier_label':    'المستوى',
  'groupbuy.progress':      'التقدم',
  'groupbuy.how_works':     'كيف يعمل؟',
  'groupbuy.step1':         'اختر عطراً',
  'groupbuy.step1_desc':    'اختر إبداعاً من LA CELLE وانضم إلى مجموعة شراء نشطة.',
  'groupbuy.step2':         'ادعُ أصدقاءك',
  'groupbuy.step2_desc':    'شارك رابطك الفريد على واتساب أو تيليغرام.',
  'groupbuy.step3':         'استمتع بسعر المجموعة',
  'groupbuy.step3_desc':    'كلما كبرت المجموعة، زاد الخصم — حتى 50%!',
  'creator.title':            'بطاقة المبدع',
  'creator.subtitle':         'برنامج سفراء LA CELLE',
  'creator.desc':             'كن سفيراً لـ Maison LA CELLE واكسب مكافآت حصرية.',
  'creator.apply':            'كن سفيراً',
  'creator.my_card':          'بطاقتي',
  'creator.stats':            'الإحصاءات',
  'creator.submissions':      'المحتوى المقدم',
  'creator.rewards':          'المكافآت',
  'creator.followers':        'المتابعون',
  'creator.credit':           'الرصيد المتاح',
  'creator.tier':             'المستوى',
  'creator.submit_content':   'تقديم محتوى',
  'creator.platform':         'المنصة',
  'creator.handle':           'المعرّف',
  'creator.content_url':      'رابط المحتوى',
  'creator.description':      'الوصف',
  'creator.submit':           'تقديم',
  'creator.pending':          'قيد المراجعة',
  'creator.approved':         'مقبول',
  'creator.rejected':         'مرفوض',
  'creator.how_works':        'كيف تعمل بطاقة المبدع؟',
  'creator.step1':            'قدّم طلبك',
  'creator.step1_desc':       'أرسل حساباتك على وسائل التواصل. يقيّم الذكاء الاصطناعي ملفك.',
  'creator.step2':            'استلم بطاقتك',
  'creator.step2_desc':       'بطاقة افتراضية بحد ائتماني حسب حجم جمهورك.',
  'creator.step3':            'أنشئ محتوى',
  'creator.step3_desc':       'شارك عالم LA CELLE وسدّد عبر منشوراتك.',
  'creator.add_account':      'إضافة حساب',
  'creator.total_followers':  'إجمالي المتابعين',
  'creator.reviewing':        'جارٍ التحليل...',
  'creator.min_followers':    'الحد الأدنى 10,000 متابع',
  'contact.title':   'اتصل بنا',
  'contact.subtitle':'تواصل معنا',
  'contact.paris':   'بوتيك باريس',
  'contact.grasse':  'ورشة غراس',
  'contact.china':   'ممثل الصين',
  'contact.name':    'الاسم',
  'contact.email':   'البريد الإلكتروني',
  'contact.subject': 'الموضوع',
  'contact.message': 'الرسالة',
  'contact.send':    'إرسال',
  'contact.sent':    'تم إرسال الرسالة',
  'footer.tagline':          '"قطرة عطر، نصف صفحة من تاريخ فرنسا."',
  'footer.maison':           'الدار',
  'footer.collections_label':'المجموعات',
  'footer.contact_label':    'اتصل بنا',
  'footer.rights':           '© 2024 LA CELLE PARIS. دار تأسست عام 1802. جميع الحقوق محفوظة.',
  'common.loading': 'جارٍ التحميل...',
  'common.error':   'حدث خطأ',
  'common.back':    'رجوع',
  'common.close':   'إغلاق',
  'common.save':    'حفظ',
  'common.cancel':  'إلغاء',
  'common.confirm': 'تأكيد',
}

const t_ja: T = {
  'nav.heritage':    '歴史',
  'nav.collections': 'コレクション',
  'nav.maison':      'Maison de Celle',
  'nav.olfactory':   '香調ノート',
  'nav.groupbuy':    'グループ購入',
  'nav.creator':     'クリエイターカード',
  'nav.contact':     'お問い合わせ',
  'hero.tagline':    '1802年創業',
  'hero.quote':      '「一滴の香水、フランス史の半ページ。」',
  'hero.cta':        '探索する',
  'hero.maison_cta': 'Maison de Celle',
  'heritage.title':           '私たちの遺産',
  'heritage.subtitle':        '二世紀のフランス香水芸術',
  'heritage.intro':           'LA CELLEは、家族の手を離れることなく二世紀の歴史を歩んできた稀有なフランス香水メゾンです。',
  'heritage.connections':     '歴史的なつながり',
  'heritage.defunct_title':   '私たちを鼓舞した消えたメゾンたち',
  'heritage.defunct_subtitle':'これらの消えたメゾンは私たちとともにフランス香水の歴史を書いた',
  'collections.title':      'コレクション',
  'collections.subtitle':   'フランス香水芸術',
  'collections.top':        'トップノート',
  'collections.heart':      'ハートノート',
  'collections.base':       'ベースノート',
  'collections.add_cart':   'カートに追加',
  'collections.discover':   '探索',
  'collections.supreme':    '至高コレクション',
  'collections.maison_cta': 'Maison de Celle',
  'collections.maison_desc':'メゾン最高峰のコレクション。最も目の肥えた鑑定家のために。',
  'maison.title':              'Maison de Celle',
  'maison.subtitle':           '絶対的な卓越性',
  'maison.philosophy':         '至高の哲学',
  'maison.per_creation':       '作品ごとの本数',
  'maison.natural':            '天然エッセンス',
  'maison.crystal':            'Saint-Louisクリスタル',
  'maison.craftsmanship':      '職人技',
  'maison.craftsmanship_title':'マスター調香師の技',
  'maison.consultation':       '特別サービス',
  'maison.consultation_title': 'プライベートコンサルテーション',
  'maison.consultation_desc':  'Maison de Celle作品のご購入には、プライベートコンサルテーションをご案内しております。',
  'maison.book':               '予約する',
  'olfactory.title':              '香調ノート',
  'olfactory.subtitle':           'アトリエ手帳',
  'olfactory.intro':              '1802年以来、マスター調香師たちはコルドバ革装丁のノートに嗅覚的発見を記録してきました。',
  'olfactory.ingredients':        '希少原料',
  'olfactory.ingredients_subtitle':'特別な原材料',
  'olfactory.training':           'トレーニング',
  'olfactory.training_title':     'LA CELLE香水学校',
  'olfactory.training_desc':      '1847年以来、メゾンは口頭伝統に従い独自のマスター調香師を育成しています。',
  'groupbuy.title':         'グループ購入',
  'groupbuy.subtitle':      '特別価格の香水',
  'groupbuy.desc':          'グループ購入に参加して特別価格をお楽しみください。',
  'groupbuy.join':          '参加する',
  'groupbuy.share':         'シェア',
  'groupbuy.people':        '人',
  'groupbuy.target':        '目標',
  'groupbuy.discount':      '割引',
  'groupbuy.expires':       '残り時間',
  'groupbuy.original':      '通常価格',
  'groupbuy.group_price':   'グループ価格',
  'groupbuy.joined':        '人が参加中',
  'groupbuy.flash':         '⚡ フラッシュセール',
  'groupbuy.mega':          '🔥 メガグループ',
  'groupbuy.standard':      '👥 スタンダードグループ',
  'groupbuy.success':       'グループに参加しました！',
  'groupbuy.share_whatsapp':'WhatsAppでシェア',
  'groupbuy.share_telegram':'Telegramでシェア',
  'groupbuy.copy_link':     'リンクをコピー',
  'groupbuy.copied':        'コピーしました！',
  'groupbuy.next_tier':     '次のティア',
  'groupbuy.more_needed':   '人でさらに割引',
  'groupbuy.join_now':      '今すぐ参加',
  'groupbuy.amount':        '金額（€）',
  'groupbuy.confirm_join':  '確認',
  'groupbuy.tier_label':    'ティア',
  'groupbuy.progress':      '進捗',
  'groupbuy.how_works':     '参加方法',
  'groupbuy.step1':         '香水を選ぶ',
  'groupbuy.step1_desc':    'LA CELLEの作品を選び、アクティブなグループに参加。',
  'groupbuy.step2':         '友人を招待',
  'groupbuy.step2_desc':    'WhatsApp、Telegramでリンクをシェア。',
  'groupbuy.step3':         'グループ価格を楽しむ',
  'groupbuy.step3_desc':    'グループが大きいほど割引も大きく — 最大50%！',
  'creator.title':            'クリエイターカード',
  'creator.subtitle':         'LA CELLEアンバサダープログラム',
  'creator.desc':             'Maison LA CELLEのアンバサダーになり特別な報酬を獲得しましょう。',
  'creator.apply':            'アンバサダーになる',
  'creator.my_card':          'マイカード',
  'creator.stats':            '統計',
  'creator.submissions':      '投稿',
  'creator.rewards':          '報酬',
  'creator.followers':        'フォロワー',
  'creator.credit':           '利用可能クレジット',
  'creator.tier':             'ティア',
  'creator.submit_content':   'コンテンツを投稿',
  'creator.platform':         'プラットフォーム',
  'creator.handle':           'アカウント',
  'creator.content_url':      'コンテンツURL',
  'creator.description':      '説明',
  'creator.submit':           '投稿',
  'creator.pending':          '審査中',
  'creator.approved':         '承認済み',
  'creator.rejected':         '却下',
  'creator.how_works':        'クリエイターカードの仕組み',
  'creator.step1':            '申請する',
  'creator.step1_desc':       'SNSアカウントを提出。AIがプロフィールを評価します。',
  'creator.step2':            'カードを受け取る',
  'creator.step2_desc':       'フォロワー数に応じたクレジット限度額の仮想カード。',
  'creator.step3':            'コンテンツを作成',
  'creator.step3_desc':       'LA CELLEの世界をシェアし、投稿でクレジットを返済。',
  'creator.add_account':      'アカウントを追加',
  'creator.total_followers':  '総フォロワー数',
  'creator.reviewing':        '分析中...',
  'creator.min_followers':    '最低10,000フォロワーが必要',
  'contact.title':   'お問い合わせ',
  'contact.subtitle':'ご連絡ください',
  'contact.paris':   'パリ ブティック',
  'contact.grasse':  'グラース アトリエ',
  'contact.china':   '中国代理店',
  'contact.name':    'お名前',
  'contact.email':   'メール',
  'contact.subject': '件名',
  'contact.message': 'メッセージ',
  'contact.send':    '送信',
  'contact.sent':    'メッセージを送信しました',
  'footer.tagline':          '「一滴の香水、フランス史の半ページ。」',
  'footer.maison':           'メゾン',
  'footer.collections_label':'コレクション',
  'footer.contact_label':    'お問い合わせ',
  'footer.rights':           '© 2024 LA CELLE PARIS. 1802年創業。無断転載禁止。',
  'common.loading': '読み込み中...',
  'common.error':   'エラーが発生しました',
  'common.back':    '戻る',
  'common.close':   '閉じる',
  'common.save':    '保存',
  'common.cancel':  'キャンセル',
  'common.confirm': '確認',
}

const t_de: T = {
  'nav.heritage':    'Erbe',
  'nav.collections': 'Kollektionen',
  'nav.maison':      'Maison de Celle',
  'nav.olfactory':   'Duftnotizen',
  'nav.groupbuy':    'Gruppenangebote',
  'nav.creator':     'Creator-Karte',
  'nav.contact':     'Kontakt',
  'hero.tagline':    'Seit 1802',
  'hero.quote':      '"Ein Tropfen Parfüm, eine halbe Seite französischer Geschichte."',
  'hero.cta':        'Entdecken',
  'hero.maison_cta': 'Maison de Celle',
  'heritage.title':           'Unser Erbe',
  'heritage.subtitle':        'Zwei Jahrhunderte Französischer Parfümerie',
  'heritage.intro':           'LA CELLE ist eines der seltenen französischen Parfümhäuser, das zwei Jahrhunderte Geschichte durchquert hat.',
  'heritage.connections':     'Historische Verbindungen',
  'heritage.defunct_title':   'Die Verschwundenen Häuser, Die Uns Inspirierten',
  'heritage.defunct_subtitle':'Diese verschwundenen Häuser schrieben gemeinsam mit uns die Geschichte der französischen Parfümerie',
  'collections.title':      'Unsere Kollektionen',
  'collections.subtitle':   'Die Kunst der Französischen Parfümerie',
  'collections.top':        'Kopfnoten',
  'collections.heart':      'Herznoten',
  'collections.base':       'Basisnoten',
  'collections.add_cart':   'In den Warenkorb',
  'collections.discover':   'Entdecken',
  'collections.supreme':    'Höchste Kollektion',
  'collections.maison_cta': 'Maison de Celle',
  'collections.maison_desc':'Die exklusivste Kollektion des Hauses für die anspruchsvollsten Kenner.',
  'maison.title':              'Maison de Celle',
  'maison.subtitle':           'Absolute Exzellenz',
  'maison.philosophy':         'Die Höchste Philosophie',
  'maison.per_creation':       'Exemplare pro Kreation',
  'maison.natural':            'Natürliche Essenzen',
  'maison.crystal':            'Saint-Louis Kristall',
  'maison.craftsmanship':      'Handwerk',
  'maison.craftsmanship_title':'Das Können der Meisterparfümeure',
  'maison.consultation':       'Exklusiver Service',
  'maison.consultation_title': 'Private Beratung',
  'maison.consultation_desc':  'Für den Erwerb einer Maison de Celle Kreation laden wir Sie zu einer privaten Beratung ein.',
  'maison.book':               'Termin Buchen',
  'olfactory.title':              'Duftnotizen',
  'olfactory.subtitle':           'Werkstatt-Tagebücher',
  'olfactory.intro':              'Seit 1802 halten die Meisterparfümeure ihre olfaktorischen Entdeckungen in kordobanisch ledergebundenen Notizbüchern fest.',
  'olfactory.ingredients':        'Seltene Zutaten',
  'olfactory.ingredients_subtitle':'Außergewöhnliche Rohstoffe',
  'olfactory.training':           'Ausbildung',
  'olfactory.training_title':     'Die LA CELLE Parfümerieakademie',
  'olfactory.training_desc':      'Seit 1847 bildet das Haus seine eigenen Meisterparfümeure nach mündlicher Tradition aus.',
  'groupbuy.title':         'Gruppenangebote',
  'groupbuy.subtitle':      'Außergewöhnliche Düfte zu Vorzugspreisen',
  'groupbuy.desc':          'Treten Sie einer Einkaufsgruppe bei und genießen Sie exklusive Preise.',
  'groupbuy.join':          'Beitreten',
  'groupbuy.share':         'Teilen',
  'groupbuy.people':        'Personen',
  'groupbuy.target':        'Ziel',
  'groupbuy.discount':      'Rabatt',
  'groupbuy.expires':       'Läuft ab in',
  'groupbuy.original':      'Originalpreis',
  'groupbuy.group_price':   'Gruppenpreis',
  'groupbuy.joined':        'haben sich der Gruppe angeschlossen',
  'groupbuy.flash':         '⚡ Flash-Angebot',
  'groupbuy.mega':          '🔥 Mega-Gruppe',
  'groupbuy.standard':      '👥 Standard-Gruppe',
  'groupbuy.success':       'Sie sind der Gruppe beigetreten!',
  'groupbuy.share_whatsapp':'Auf WhatsApp teilen',
  'groupbuy.share_telegram':'Auf Telegram teilen',
  'groupbuy.copy_link':     'Link kopieren',
  'groupbuy.copied':        'Link kopiert!',
  'groupbuy.next_tier':     'Nächste Stufe',
  'groupbuy.more_needed':   'Personen mehr für',
  'groupbuy.join_now':      'Jetzt Beitreten',
  'groupbuy.amount':        'Betrag (€)',
  'groupbuy.confirm_join':  'Bestätigen',
  'groupbuy.tier_label':    'Stufe',
  'groupbuy.progress':      'Fortschritt',
  'groupbuy.how_works':     'Wie funktioniert es?',
  'groupbuy.step1':         'Wählen Sie einen Duft',
  'groupbuy.step1_desc':    'Wählen Sie eine LA CELLE Kreation und treten Sie einer aktiven Gruppe bei.',
  'groupbuy.step2':         'Laden Sie Freunde ein',
  'groupbuy.step2_desc':    'Teilen Sie Ihren einzigartigen Link auf WhatsApp oder Telegram.',
  'groupbuy.step3':         'Genießen Sie den Gruppenpreis',
  'groupbuy.step3_desc':    'Je größer die Gruppe, desto größer der Rabatt — bis zu 50%!',
  'creator.title':            'Creator-Karte',
  'creator.subtitle':         'LA CELLE Botschafter-Programm',
  'creator.desc':             'Werden Sie Botschafter der Maison LA CELLE und verdienen Sie exklusive Belohnungen.',
  'creator.apply':            'Botschafter Werden',
  'creator.my_card':          'Meine Karte',
  'creator.stats':            'Statistiken',
  'creator.submissions':      'Einreichungen',
  'creator.rewards':          'Belohnungen',
  'creator.followers':        'Follower',
  'creator.credit':           'Verfügbares Guthaben',
  'creator.tier':             'Stufe',
  'creator.submit_content':   'Inhalt Einreichen',
  'creator.platform':         'Plattform',
  'creator.handle':           'Benutzername',
  'creator.content_url':      'Inhalts-URL',
  'creator.description':      'Beschreibung',
  'creator.submit':           'Einreichen',
  'creator.pending':          'Ausstehend',
  'creator.approved':         'Genehmigt',
  'creator.rejected':         'Abgelehnt',
  'creator.how_works':        'Wie funktioniert die Creator-Karte?',
  'creator.step1':            'Bewerben',
  'creator.step1_desc':       'Reichen Sie Ihre Social-Media-Konten ein. Unsere KI bewertet Ihr Profil.',
  'creator.step2':            'Karte erhalten',
  'creator.step2_desc':       'Eine virtuelle Karte mit Kreditlimit basierend auf Ihrer Reichweite.',
  'creator.step3':            'Inhalte erstellen',
  'creator.step3_desc':       'Teilen Sie das LA CELLE-Universum und begleichen Sie den Kredit durch Veröffentlichungen.',
  'creator.add_account':      'Konto hinzufügen',
  'creator.total_followers':  'Gesamt-Follower',
  'creator.reviewing':        'Analysiere...',
  'creator.min_followers':    'Mindestens 10.000 Follower erforderlich',
  'contact.title':   'Kontakt',
  'contact.subtitle':'Kontaktieren Sie Uns',
  'contact.paris':   'Boutique Paris',
  'contact.grasse':  'Atelier Grasse',
  'contact.china':   'China-Vertreter',
  'contact.name':    'Name',
  'contact.email':   'E-Mail',
  'contact.subject': 'Betreff',
  'contact.message': 'Nachricht',
  'contact.send':    'Senden',
  'contact.sent':    'Nachricht gesendet',
  'footer.tagline':          '"Ein Tropfen Parfüm, eine halbe Seite französischer Geschichte."',
  'footer.maison':           'Maison',
  'footer.collections_label':'Kollektionen',
  'footer.contact_label':    'Kontakt',
  'footer.rights':           '© 2024 LA CELLE PARIS. Haus gegründet 1802. Alle Rechte vorbehalten.',
  'common.loading': 'Laden...',
  'common.error':   'Etwas ist schiefgelaufen',
  'common.back':    'Zurück',
  'common.close':   'Schließen',
  'common.save':    'Speichern',
  'common.cancel':  'Abbrechen',
  'common.confirm': 'Bestätigen',
}

export const translations: Record<Lang, T> = {
  fr: t_fr, en: t_en, zh: t_zh, es: t_es, ru: t_ru, ar: t_ar, ja: t_ja, de: t_de,
}

// ─── Context ──────────────────────────────────────────────────────────────────
interface LanguageContextType {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: string) => string
  isCN: boolean
  isRTL: boolean
  dir: 'ltr' | 'rtl'
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'fr',
  setLang: () => {},
  t: (k) => k,
  isCN: false,
  isRTL: false,
  dir: 'ltr',
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem('lacelle_lang') as Lang
    if (saved && translations[saved]) return saved
    const browser = navigator.language.toLowerCase()
    if (browser.startsWith('zh')) return 'zh'
    if (browser.startsWith('fr')) return 'fr'
    if (browser.startsWith('es')) return 'es'
    if (browser.startsWith('ru')) return 'ru'
    if (browser.startsWith('ar')) return 'ar'
    if (browser.startsWith('ja')) return 'ja'
    if (browser.startsWith('de')) return 'de'
    return 'fr'
  })

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('lacelle_lang', l)
  }

  const t = (key: string): string =>
    translations[lang]?.[key] ?? translations['fr']?.[key] ?? key

  const currentMeta = LANGUAGES.find(l => l.code === lang)
  const dir = currentMeta?.dir ?? 'ltr'
  const isRTL = dir === 'rtl'

  useEffect(() => {
    document.documentElement.setAttribute('dir', dir)
    document.documentElement.setAttribute('lang', lang)
  }, [lang, dir])

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isCN: lang === 'zh', isRTL, dir }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
